name: Build RediSearch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Redis
      uses: redislabs/redis-enterprise-docker@v1
      with:
        redis_version: 6.2.5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build RediSearch
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload shared library
      uses: actions/upload-artifact@v2
      with:
        name: rediSearch-shared-library
        path: build/src/redisearch.so
