name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Draft release
      uses: release-drafter/release-drafter@v5.21.0
      with:
        config-name: .github/release-drafter-config.yml
